-- Incersión de productos
INSERT INTO `shopgamers`.`productos` (`id`, `imagen1`, `nombre`, `descripcion1`, `descripcion2`, `precio`, `imagen2`)
VALUES (NULL, "img/productos/producto1.webp","Fifa 2022", "EA SPORTS FIFA 22 acerca el juego a la realidad como nunca antes.","Las nuevas características de juego de FIFA 22 te dan mayor regularidad entre los palos con la nueva mecánica de los porteros que le añade compostura a la posición más importante de la cancha, además de una nueva física del balón, un sprint explosivo que coincide mejor con la aceleración de los jugadores más rápidos y nuevas tácticas ofensivas que te permiten controlar la manera en que juega tu equipo. En el modo Carrera, vive tus sueños futbolísticos mientras creas y diriges el club más nuevo del juego hacia la gloria. VOLTA FOOTBALL te recompensa por tu estilo con un rediseño del futbol reducido y nuevas formas de jugar y progresar cada temporada. Arma la plantilla en Clubes Pro con la personalización de equipo mejorada y el progreso actualizado que te permite controlar el desarrollo de tu JP. Además, celebra a algunos de los jugadores más memorables del futbol con los nuevos Héroes FUT en FIFA Ultimate Team?, con una estructura de competencia redefinida que te permitirá probar tus habilidades contra otros jugadores con más facilidad. Sin importar cómo juegues, disfruta de una autenticidad sin igual con más de 17,000 jugadores, más de 700 equipos y más de 30 ligas, incluidas la UEFA Champions League, la CONMEBOL Libertadores y la flamante UEFA Europa Conference League, solo disponibles en FIFA 22.", 800, "img/productos/producto1img2.webp");
INSERT INTO `shopgamers`.`productos` (`id`, `imagen1`, `nombre`, `descripcion1`, `descripcion2`, `precio`, `imagen2`)
VALUES (NULL, "img/productos/producto2.webp","Dark Souls III", "Es un videojuego de rol de acción, desarrollado por FromSoftware","Incluye el juego completo y el pase de temporada. El primer contenido descargable llega en el otoño 2016. Amplía tu experiencia con el pase de temporada, que presenta nuevos mapas, jefes, enemigos, armas y conjuntos de armadura adicionales. ""Mejor juego de rol"" de la Gamescom 2015 y más de 35 premios y nominaciones en la E3 2015. Dark Souls continúa redefiniendo los límites con el nuevo y ambicioso capítulo de esta serie revolucionaria, tan aclamada por la crítica. Adéntrate en un universo lleno de enemigos y entornos descomunales, un mundo en ruinas en el que las llamas se están apagando. Los jugadores se sumergirán en la atmósfera épica de un mundo de oscuridad gracias a un juego más rápido y una intensidad de combate ampliada. Solo quedan las brasas... ¡Prepárate una vez más para sumergirte en la oscuridad!", 500, "img/productos/producto2img2.webp");
INSERT INTO `shopgamers`.`productos` (`id`, `imagen1`, `nombre`, `descripcion1`, `descripcion2`, `precio`, `imagen2`)
VALUES (NULL, "img/productos/producto3.webp","COD Black Ops III", "Combina tres modos de juego únicos: campaña, multijugador y Zombis.","Ofrece a los fans el juego más profundo y ambicioso de la historia de Call of Duty. La campaña es una experiencia cooperativa en línea para hasta cuatro jugadores, pero también una emocionante aventura cinemática en solitario. El multijugador será el más profundo y cautivador de la franquicia hasta la fecha, con nuevas formas de ascender de rango y personalizar y preparar la batalla. Y Zombis ofrece una nueva experiencia espectacular con su propia historia. El título alcanza un nivel de innovación sin precedentes, que incluye entornos espectaculares, armamento y habilidades nunca vistos y un nuevo sistema mejorado de movimiento fluido.", 300, "img/productos/producto3img2.webp");
INSERT INTO `shopgamers`.`productos` (`id`, `imagen1`, `nombre`, `descripcion1`, `descripcion2`, `precio`, `imagen2`)
VALUES (NULL, "img/productos/producto4.webp","The witcher Wild Hunt", "Localizar a la Niña de la Profecía, un arma viviente que puede alterar la forma del mundo.","Conviértete en un cazamonstruos profesional y emprende una aventura de proporciones épicas! Inmediatamente después de su lanzamiento, The Witcher 3: Wild Hunt se convirtió en un clásico y ganó más de 250 premios al juego del año. Ahora puedes disfrutar de esta enorme aventura de mundo abierto de más de 100 horas de duración junto con sus dos expansiones narrativas que agregan otras 50 horas de juego. Esta edición incluye todo el contenido adicional: nuevas armas, armaduras, atuendos complementarios y misiones secundarias, y un nuevo modo de juego.", 600, "img/productos/producto4img2.webp");
INSERT INTO `shopgamers`.`productos` (`id`, `imagen1`, `nombre`, `descripcion1`, `descripcion2`, `precio`, `imagen2`)
VALUES (NULL, "img/productos/producto5.webp","Red Dead Redemption II", "Historia épica sobre el honor y la lealtad en los albores del siglo XX.","Estados Unidos, 1899. Arthur Morgan y la banda de Van der Linde son forajidos buscados. Con agentes federales y los mejores cazarrecompensas pisándoles los talones, la banda deberá abrirse camino por el salvaje territorio del corazón de Estados Unidos a base de robos y peleas para sobrevivir. Mientras las divisiones internas aumentan y amenazan con desmantelar el grupo, Arthur debe elegir entre sus propios ideales y la lealtad a la banda que lo vio crecer.", 400, "img/productos/producto5img2.webp");
INSERT INTO `shopgamers`.`productos` (`id`, `imagen1`, `nombre`, `descripcion1`, `descripcion2`, `precio`, `imagen2`)
VALUES (NULL, "img/productos/producto6.webp","Batman Arkham Knight", "Es un videojuego de acción-aventura, mundo abierto","Transcurre un año después de los acontecimientos del anterior juego, 'Batman: Arkham City', publicado en 2011. La trama principal continúa con Batman, en la cúspide de sus habilidades, enfrentándose contra el Espantapájaros, que ha lanzado un ataque contra la ciudad de Gotham, provocando la evacuación de todos sus habitantes. Espantapájaros, con la ayuda del misterioso Arkham Knight, ha sido capaz de reunir a los mayores enemigos de Batman en un intento final por destruirlo.", 400, "img/productos/producto6img2.webp");
INSERT INTO `shopgamers`.`productos` (`id`, `imagen1`, `nombre`, `descripcion1`, `descripcion2`, `precio`, `imagen2`)
VALUES (NULL, "img/productos/producto7.webp","Dead by Daylight", "Es un juego de horror en modo multijugador de 1 contra 4","Dead by Daylight es un juego de horror en modo multijugador de 1 contra 4 donde una persona asume el papel del despiadado asesino y las otras cuatro juegan como sobrevivientes que buscan escapar del asesino mientras evitan que los capturen, los torturen y los maten. Los sobrevivientes juegan desde una perspectiva en tercera persona y ven mejor el entorno. El asesino juega desde una perspectiva en primera persona y se enfoca en atrapar a su presa.", 290, "img/productos/producto7img2.webp");
INSERT INTO `shopgamers`.`productos` (`id`, `imagen1`, `nombre`, `descripcion1`, `descripcion2`, `precio`, `imagen2`)
VALUES (NULL, "img/productos/producto8.webp","Doom Eternal", "Es un videojuego de acción y disparos en primera persona","Disfruta de la mejor combinación de velocidad y potencia mientras te abres camino por las dimensiones con el próximo salto en el combate en primera persona. Raze Hell, salva a la humanidad y descubre los orígenes de Slayer en DOOM Eternal. Desarrollado por id Software, DOOM® Eternal es la continuación directa de DOOM®, ganador del Mejor juego de acción de 2016 de The Game Awards. Desarrollado por idTech 7 y configurado con una banda sonora completamente nueva compuesta por Mick Gordon, DOOM Eternal te da control del imparable DOOM Slayer mientras destruyes demonios nuevos y clásicos con armas poderosas en mundos increíbles y jamás vistos. HDR: funcionalidad HDR disponible con juegos y televisiones compatibles.", 140, "img/productos/producto8img2.webp");
INSERT INTO `shopgamers`.`productos` (`id`, `imagen1`, `nombre`, `descripcion1`, `descripcion2`, `precio`, `imagen2`)
VALUES (NULL, "img/productos/producto9.webp","Resident Evil 3", "Experimenta una terrorífica campaña para un jugador y un frenético multijugador online","Una serie de extrañas desapariciones han estado ocurriendo en la región medio-oeste de los Estados Unidos, en un lugar llamado Raccoon City. Un escuadrón especial de las fuerzas de policía conocido como S.T.A.R.S. ha estado investigando el caso, y han determinado que la compañía farmacéutica Umbrella y su arma biológica, el virus T, son responsables de estos incidentes. Tras perder a varios miembros durante la investigación, Jill Valentine y el resto de miembros supervivientes de S.T.A.R.S. siguen tratando de sacar a la luz la verdad, pero se encuentran con que el mismo departamento de policía está bajo la influencia de Umbrella, y por ello sus informes son descartados sin que puedan hacer nada al respecto.", 190, "img/productos/producto9img2.webp");
INSERT INTO `shopgamers`.`productos` (`id`, `imagen1`, `nombre`, `descripcion1`, `descripcion2`, `precio`, `imagen2`)
VALUES (NULL, "img/productos/producto10.webp","No Man's Sky", "Este juego presenta un mundo abierto generado por procedimientos.","El gameplay de No Man's Sky se basa en dos pilares —exploración y comercio— Mediante la exploración los jugadores ganarán información acerca de los planetas que podrán incluir en el Atlas, una base de datos universal que podrá ser compartida con otros jugadores del juego. Los jugadores son recompensados con dinero del juego cada vez que es incorporada nueva información en el Atlas. Los jugadores además ganan materiales y recetas para mejorar el equipo de su personaje y comprar una pequeña variedad de naves espaciales, permitiéndoles viajar más profundamente hacia el centro de la galaxia, ver planetas con entornos hostiles o comerciar con otras naves. Algunas actividades, tales como matar formas de vida o extraer recursos de los planetas atraerá la atención de los Centinelas, que intentarán matar a nuestro jugador si nos escanea mientras hacemos la acción.", 600, "img/productos/producto10img2.webp");
INSERT INTO `shopgamers`.`productos` (`id`, `imagen1`, `nombre`, `descripcion1`, `descripcion2`, `precio`, `imagen2`)
VALUES (NULL, "img/productos/producto11.webp","HotWheels Unleashed", "Colecciona los mejores vehículos del universo de Hot Wheels™","Demuestra tus habilidades y compite en carreras increíbles llenas de diversión! Derrapa, aumenta el impulso y lánzate hacia los asombrosos bucles. ¡Pero cuidado! Si disminuyes la velocidad, la gravedad hará su trabajo. Cuanto más grande sea el reto, mayor será la gloria. Corre junto a tus amigos en el modo de pantalla dividida para 2 jugadores o enfrenta hasta 12 oponentes en los desafíos en línea.", 110, "img/productos/producto11img2.webp");
INSERT INTO `shopgamers`.`productos` (`id`, `imagen1`, `nombre`, `descripcion1`, `descripcion2`, `precio`, `imagen2`)
VALUES (NULL, "img/productos/producto12.webp","Skyrim", "Es un ARPG del tipo mundo abierto ","La historia de Skyrim se centra en los esfuerzos del personaje, Dovahkiin (sangre de dragón), para derrotar a Alduin, un dragón/dovah que, según la profecía, destruirá el mundo. La trama está fechada doscientos años después de los sucesos de Oblivion y tiene lugar en la provincia ficticia de Skyrim 3​. En el transcurso de la partida, el jugador completa misiones y hace evolucionar a su personaje gracias a la mejora de sus habilidades. A diferencia de los juegos anteriores de Elder Scrolls, en Skyrim no se requiere que el usuario seleccione un tipo de personaje al inicio del juego, resolviendo así el problema que el equipo de desarrolladores veía desde versiones anteriores: la necesidad de tener que forzar al usuario a un estilo rígido de juego. Skyrim continúa con la tradición de mundo abierto al permitir que el jugador viaje a cualquier parte del mapa del juego en cualquier momento y posponerlo indefinidamente u omitir parcial o totalmente la historia principal.", 1000, "img/productos/producto12img2.webp");


-- Inserción tabla Usuarios
INSERT INTO `shopgamers`.`usuarios` (`id`, `nombre`, `apellido`, `numero`, `correo`, `contraseña`)
VALUES (NULL, "Arturo","Contreras", "6456543212","contrerarschaparroarturo@gmail.com","Pajaro6*");
INSERT INTO `shopgamers`.`usuarios` (`id`, `nombre`, `apellido`, `numero`, `correo`, `contraseña`)
VALUES (NULL, "Hugo","Sifuentes", "6391102321","sifuentesHugo34@gmail.com","taquitosDe5^*");
INSERT INTO `shopgamers`.`usuarios` (`id`, `nombre`, `apellido`, `numero`, `correo`, `contraseña`)
VALUES (NULL, "Jorge","Campos", "6147650989","jorgeelportero12@gmail.com","VivVaNs56*");
INSERT INTO `shopgamers`.`usuarios` (`id`, `nombre`, `apellido`, `numero`, `correo`, `contraseña`)
VALUES (NULL, "Elizabeth","Olsen", "5558091234","elizabethlabrujita21@hotmail.com","Wandas56$*");
INSERT INTO `shopgamers`.`usuarios` (`id`, `nombre`, `apellido`, `numero`, `correo`, `contraseña`)
VALUES (NULL, "Omar","Moreno", "6278546790","morenomarogaz63@gmail.com","Siuuuu6789#*");


-- Inserción tabla Ventas
INSERT INTO `shopgamers`.`ventas` (`id`, `fecha`, `precio_total`, `usuarios_id`, `productos_id`)
VALUES (NULL, "2022-07-05", 300, 2, 3);
INSERT INTO `shopgamers`.`ventas` (`id`, `fecha`, `precio_total`, `usuarios_id`, `productos_id`)
VALUES (NULL, "2022-05-02", 400, 3, 6);
INSERT INTO `shopgamers`.`ventas` (`id`, `fecha`, `precio_total`, `usuarios_id`, `productos_id`)
VALUES (NULL, "2022-06-23", 140, 4, 8);
INSERT INTO `shopgamers`.`ventas` (`id`, `fecha`, `precio_total`, `usuarios_id`, `productos_id`)
VALUES (NULL, "2022-07-25", 600, 1, 10);
INSERT INTO `shopgamers`.`ventas` (`id`, `fecha`, `precio_total`, `usuarios_id`, `productos_id`)
VALUES (NULL, "2022-06-29", 1000, 5, 12);